<div class="container">
    <div class="row">
        <div class="col-md-4">
            <a href="?fairy=wolf and the seven young kids" class="card" style="width: 18rem;">
                <img class="card-img-top" src="img/twatsyk.jpg" alt="The wolf and the seven young kids">
                <div class="card-body">
                    <p class="card-text text-dark font-weight-bold">The wolf and the seven young kids</p>
                </div>
            </a>
        </div>
    </div>
</div>