<title>Fairy Tale Generator</title>
<link href="https://ex.nvg-group.com/libs/mdb/4.1.1/f.min.css" rel="stylesheet" type="text/css" media="all"/>
<link href="css/styles.min.css?" rel="stylesheet" type="text/css" media="all"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="owner" content="Alexandr Vopilov">
<meta name="author" content="Alexandr Vopilov">

<script src="https://ex.nvg-group.com/libs/jquery/3.4.1/f.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.1.1/popper.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.1.1/f.js"></script>
<script src="https://ex.nvg-group.com/libs/nvg/7.7/f.min.js"></script>