<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Fairy Tale Generator</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="menu">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Все сказки</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Об авторе</a>
            </li>
        </ul>
        <form method="GET" action="?" class="form-inline my-2 my-lg-0">
            <input name="fairy" class="form-control mr-sm-2" type="search" placeholder="Сказка" aria-label="Сказка">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Найти</button>
        </form>
    </div>
</nav>